### ISSUE TITLE
How to run - improvements

### ISSUE THREAD

**Issue by petrsvihlik** [RadoslavK/jekyll-blog#1]
- Step 1 - It's good to mention that MSYS2 needs to be installed as well
- Steps 1 and 3 of the [how to run](https://github.com/RadoslavK/jekyll-blog#how-to-run) tutorial require administrator privileges.
- Step 8 - "Set PROJECT_ID and DELIVERY_API_KEY environment variables. " where? in the _config.yml? if so, add it there
- Step 10 - even though I followed the steps, I'm getting this after I run `bundle exec jekyll build`:
>bundler: command not found: jekyll
Install missing gem executables with `bundle install`

**Comment by RadoslavK** [comment]
- MSYS2 should be installed with DevKit but I have added it so it is explicit

- Note added

- They should be set in system environment variables, added to the guide

- Bundler probably failed to install due to the previous issues or it is being overridden by the bundler version installed by Ruby ENV. Or it is just the Jekyll failing to install. I will look into it

**Comment by petrsvihlik** [comment]
system environment variables - wth?

**Comment by RadoslavK** [comment]
in operating system

**Comment by petrsvihlik** [comment]
yes and the question remains - why the hell would you put something like that into system variables? :D

**Comment by RadoslavK** [comment]
Well, you can either put the secret directly into the config/repository file or set up an environment variable but I guess for the tutorial purpose it can stay in the config then.

**Comment by petrsvihlik** [comment]
oh, I get it. well, there should be two ways to configure it for sure:

1. env variable - for CI agents
2. config - for development environments

**Comment by RadoslavK** [comment]
Both ways are possible, just wanted to show an example. So I will keep it in the config for this tutorial.
